# Generated by Django 5.1.4 on 2024-12-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sessions',
            table='sessions_tb',
        ),
    ]
