# Generated by Django 5.1.4 on 2024-12-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_page', '0003_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='event_page.events'),
        ),
    ]
