# Generated by Django 5.1.4 on 2024-12-19 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_page', '0004_alter_sessions_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='event_id',
            new_name='event',
        ),
    ]
